// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: netcluster/message.proto

package netcluster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Master_PublishServerStatus struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ServerId                 uint32                 `protobuf:"varint,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"`
	ServerType               uint32                 `protobuf:"varint,2,opt,name=ServerType,proto3" json:"ServerType,omitempty"`
	IsConnected              bool                   `protobuf:"varint,3,opt,name=IsConnected,proto3" json:"IsConnected,omitempty"`
	IsWorking                bool                   `protobuf:"varint,4,opt,name=IsWorking,proto3" json:"IsWorking,omitempty"`
	DisableNewConsistentFLow bool                   `protobuf:"varint,5,opt,name=DisableNewConsistentFLow,proto3" json:"DisableNewConsistentFLow,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Master_PublishServerStatus) Reset() {
	*x = Master_PublishServerStatus{}
	mi := &file_netcluster_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Master_PublishServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Master_PublishServerStatus) ProtoMessage() {}

func (x *Master_PublishServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Master_PublishServerStatus.ProtoReflect.Descriptor instead.
func (*Master_PublishServerStatus) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{0}
}

func (x *Master_PublishServerStatus) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *Master_PublishServerStatus) GetServerType() uint32 {
	if x != nil {
		return x.ServerType
	}
	return 0
}

func (x *Master_PublishServerStatus) GetIsConnected() bool {
	if x != nil {
		return x.IsConnected
	}
	return false
}

func (x *Master_PublishServerStatus) GetIsWorking() bool {
	if x != nil {
		return x.IsWorking
	}
	return false
}

func (x *Master_PublishServerStatus) GetDisableNewConsistentFLow() bool {
	if x != nil {
		return x.DisableNewConsistentFLow
	}
	return false
}

type Slave_ReportLoadLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFix         bool                   `protobuf:"varint,1,opt,name=isFix,proto3" json:"isFix,omitempty"`
	AServerID     uint32                 `protobuf:"varint,2,opt,name=AServerID,proto3" json:"AServerID,omitempty"`
	BServerID     uint32                 `protobuf:"varint,3,opt,name=BServerID,proto3" json:"BServerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slave_ReportLoadLevel) Reset() {
	*x = Slave_ReportLoadLevel{}
	mi := &file_netcluster_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slave_ReportLoadLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slave_ReportLoadLevel) ProtoMessage() {}

func (x *Slave_ReportLoadLevel) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slave_ReportLoadLevel.ProtoReflect.Descriptor instead.
func (*Slave_ReportLoadLevel) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{1}
}

func (x *Slave_ReportLoadLevel) GetIsFix() bool {
	if x != nil {
		return x.IsFix
	}
	return false
}

func (x *Slave_ReportLoadLevel) GetAServerID() uint32 {
	if x != nil {
		return x.AServerID
	}
	return 0
}

func (x *Slave_ReportLoadLevel) GetBServerID() uint32 {
	if x != nil {
		return x.BServerID
	}
	return 0
}

type Master_PublishLoadLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoadLevel     uint32                 `protobuf:"varint,1,opt,name=LoadLevel,proto3" json:"LoadLevel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Master_PublishLoadLevel) Reset() {
	*x = Master_PublishLoadLevel{}
	mi := &file_netcluster_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Master_PublishLoadLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Master_PublishLoadLevel) ProtoMessage() {}

func (x *Master_PublishLoadLevel) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Master_PublishLoadLevel.ProtoReflect.Descriptor instead.
func (*Master_PublishLoadLevel) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{2}
}

func (x *Master_PublishLoadLevel) GetLoadLevel() uint32 {
	if x != nil {
		return x.LoadLevel
	}
	return 0
}

type Slave_ReqShiftFixMaster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterID      uint32                 `protobuf:"varint,1,opt,name=MasterID,proto3" json:"MasterID,omitempty"`
	AServerID     uint32                 `protobuf:"varint,2,opt,name=AServerID,proto3" json:"AServerID,omitempty"`
	BServerID     uint32                 `protobuf:"varint,3,opt,name=BServerID,proto3" json:"BServerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slave_ReqShiftFixMaster) Reset() {
	*x = Slave_ReqShiftFixMaster{}
	mi := &file_netcluster_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slave_ReqShiftFixMaster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slave_ReqShiftFixMaster) ProtoMessage() {}

func (x *Slave_ReqShiftFixMaster) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slave_ReqShiftFixMaster.ProtoReflect.Descriptor instead.
func (*Slave_ReqShiftFixMaster) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{3}
}

func (x *Slave_ReqShiftFixMaster) GetMasterID() uint32 {
	if x != nil {
		return x.MasterID
	}
	return 0
}

func (x *Slave_ReqShiftFixMaster) GetAServerID() uint32 {
	if x != nil {
		return x.AServerID
	}
	return 0
}

func (x *Slave_ReqShiftFixMaster) GetBServerID() uint32 {
	if x != nil {
		return x.BServerID
	}
	return 0
}

type Slave_RepShiftFixMaster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterID      uint32                 `protobuf:"varint,1,opt,name=MasterID,proto3" json:"MasterID,omitempty"`
	AServerID     uint32                 `protobuf:"varint,2,opt,name=AServerID,proto3" json:"AServerID,omitempty"`
	BServerID     uint32                 `protobuf:"varint,3,opt,name=BServerID,proto3" json:"BServerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slave_RepShiftFixMaster) Reset() {
	*x = Slave_RepShiftFixMaster{}
	mi := &file_netcluster_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slave_RepShiftFixMaster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slave_RepShiftFixMaster) ProtoMessage() {}

func (x *Slave_RepShiftFixMaster) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slave_RepShiftFixMaster.ProtoReflect.Descriptor instead.
func (*Slave_RepShiftFixMaster) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{4}
}

func (x *Slave_RepShiftFixMaster) GetMasterID() uint32 {
	if x != nil {
		return x.MasterID
	}
	return 0
}

func (x *Slave_RepShiftFixMaster) GetAServerID() uint32 {
	if x != nil {
		return x.AServerID
	}
	return 0
}

func (x *Slave_RepShiftFixMaster) GetBServerID() uint32 {
	if x != nil {
		return x.BServerID
	}
	return 0
}

type Slave_ReqVerifyConfigFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileMd5       string                 `protobuf:"bytes,1,opt,name=FileMd5,proto3" json:"FileMd5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slave_ReqVerifyConfigFile) Reset() {
	*x = Slave_ReqVerifyConfigFile{}
	mi := &file_netcluster_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slave_ReqVerifyConfigFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slave_ReqVerifyConfigFile) ProtoMessage() {}

func (x *Slave_ReqVerifyConfigFile) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slave_ReqVerifyConfigFile.ProtoReflect.Descriptor instead.
func (*Slave_ReqVerifyConfigFile) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{5}
}

func (x *Slave_ReqVerifyConfigFile) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

type Master_ReqVerifyConfigFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileMd5       string                 `protobuf:"bytes,1,opt,name=FileMd5,proto3" json:"FileMd5,omitempty"`
	Time          int64                  `protobuf:"varint,2,opt,name=Time,proto3" json:"Time,omitempty"`
	ReqServerId   uint32                 `protobuf:"varint,3,opt,name=ReqServerId,proto3" json:"ReqServerId,omitempty"`
	ReqServerType uint32                 `protobuf:"varint,4,opt,name=ReqServerType,proto3" json:"ReqServerType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Master_ReqVerifyConfigFile) Reset() {
	*x = Master_ReqVerifyConfigFile{}
	mi := &file_netcluster_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Master_ReqVerifyConfigFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Master_ReqVerifyConfigFile) ProtoMessage() {}

func (x *Master_ReqVerifyConfigFile) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Master_ReqVerifyConfigFile.ProtoReflect.Descriptor instead.
func (*Master_ReqVerifyConfigFile) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{6}
}

func (x *Master_ReqVerifyConfigFile) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

func (x *Master_ReqVerifyConfigFile) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Master_ReqVerifyConfigFile) GetReqServerId() uint32 {
	if x != nil {
		return x.ReqServerId
	}
	return 0
}

func (x *Master_ReqVerifyConfigFile) GetReqServerType() uint32 {
	if x != nil {
		return x.ReqServerType
	}
	return 0
}

type Slave_RepVerifyConfigFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSucc        bool                   `protobuf:"varint,1,opt,name=IsSucc,proto3" json:"IsSucc,omitempty"`
	Time          int64                  `protobuf:"varint,2,opt,name=Time,proto3" json:"Time,omitempty"`
	ReqServerId   uint32                 `protobuf:"varint,3,opt,name=ReqServerId,proto3" json:"ReqServerId,omitempty"`
	ReqServerType uint32                 `protobuf:"varint,4,opt,name=ReqServerType,proto3" json:"ReqServerType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slave_RepVerifyConfigFile) Reset() {
	*x = Slave_RepVerifyConfigFile{}
	mi := &file_netcluster_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slave_RepVerifyConfigFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slave_RepVerifyConfigFile) ProtoMessage() {}

func (x *Slave_RepVerifyConfigFile) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slave_RepVerifyConfigFile.ProtoReflect.Descriptor instead.
func (*Slave_RepVerifyConfigFile) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{7}
}

func (x *Slave_RepVerifyConfigFile) GetIsSucc() bool {
	if x != nil {
		return x.IsSucc
	}
	return false
}

func (x *Slave_RepVerifyConfigFile) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Slave_RepVerifyConfigFile) GetReqServerId() uint32 {
	if x != nil {
		return x.ReqServerId
	}
	return 0
}

func (x *Slave_RepVerifyConfigFile) GetReqServerType() uint32 {
	if x != nil {
		return x.ReqServerType
	}
	return 0
}

type Slave_UptConfigMd5 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileMd5       string                 `protobuf:"bytes,1,opt,name=FileMd5,proto3" json:"FileMd5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slave_UptConfigMd5) Reset() {
	*x = Slave_UptConfigMd5{}
	mi := &file_netcluster_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slave_UptConfigMd5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slave_UptConfigMd5) ProtoMessage() {}

func (x *Slave_UptConfigMd5) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slave_UptConfigMd5.ProtoReflect.Descriptor instead.
func (*Slave_UptConfigMd5) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{8}
}

func (x *Slave_UptConfigMd5) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

// gm命令slave准备停止服务(slave->slave)
type SS_CmdPrepareCloseServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SS_CmdPrepareCloseServer) Reset() {
	*x = SS_CmdPrepareCloseServer{}
	mi := &file_netcluster_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SS_CmdPrepareCloseServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SS_CmdPrepareCloseServer) ProtoMessage() {}

func (x *SS_CmdPrepareCloseServer) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SS_CmdPrepareCloseServer.ProtoReflect.Descriptor instead.
func (*SS_CmdPrepareCloseServer) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{9}
}

// 我要准备关闭了 (slave->master)
type SM_ReqPrepareCloseMyself struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SM_ReqPrepareCloseMyself) Reset() {
	*x = SM_ReqPrepareCloseMyself{}
	mi := &file_netcluster_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SM_ReqPrepareCloseMyself) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_ReqPrepareCloseMyself) ProtoMessage() {}

func (x *SM_ReqPrepareCloseMyself) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_ReqPrepareCloseMyself.ProtoReflect.Descriptor instead.
func (*SM_ReqPrepareCloseMyself) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{10}
}

// slave->slave 通知关闭服务
type SS_CmdCloseServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SS_CmdCloseServer) Reset() {
	*x = SS_CmdCloseServer{}
	mi := &file_netcluster_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SS_CmdCloseServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SS_CmdCloseServer) ProtoMessage() {}

func (x *SS_CmdCloseServer) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SS_CmdCloseServer.ProtoReflect.Descriptor instead.
func (*SS_CmdCloseServer) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{11}
}

// adminsvr 发送gm命令，让某些slave不再接入新用户的请求 （不影响旧用户，旧用户仍可以正常享有这些slave的服务）
type S2S_CmdUnloadServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2S_CmdUnloadServer) Reset() {
	*x = S2S_CmdUnloadServer{}
	mi := &file_netcluster_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2S_CmdUnloadServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2S_CmdUnloadServer) ProtoMessage() {}

func (x *S2S_CmdUnloadServer) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2S_CmdUnloadServer.ProtoReflect.Descriptor instead.
func (*S2S_CmdUnloadServer) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{12}
}

// (slave->master) slave告知master，已经绑定“我”的旧用户的请求仍然交给”我“处理，但“我”不再接受新用户的请求，对新用户的请求做负载均衡的时候别把“我”算进去
type S2M_ReqUnloadMyself struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2M_ReqUnloadMyself) Reset() {
	*x = S2M_ReqUnloadMyself{}
	mi := &file_netcluster_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2M_ReqUnloadMyself) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2M_ReqUnloadMyself) ProtoMessage() {}

func (x *S2M_ReqUnloadMyself) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2M_ReqUnloadMyself.ProtoReflect.Descriptor instead.
func (*S2M_ReqUnloadMyself) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{13}
}

var File_netcluster_message_proto protoreflect.FileDescriptor

const file_netcluster_message_proto_rawDesc = "" +
	"\n" +
	"\x18netcluster/message.proto\x12\n" +
	"netcluster\"\xd4\x01\n" +
	"\x1aMaster_PublishServerStatus\x12\x1a\n" +
	"\bServerId\x18\x01 \x01(\rR\bServerId\x12\x1e\n" +
	"\n" +
	"ServerType\x18\x02 \x01(\rR\n" +
	"ServerType\x12 \n" +
	"\vIsConnected\x18\x03 \x01(\bR\vIsConnected\x12\x1c\n" +
	"\tIsWorking\x18\x04 \x01(\bR\tIsWorking\x12:\n" +
	"\x18DisableNewConsistentFLow\x18\x05 \x01(\bR\x18DisableNewConsistentFLow\"i\n" +
	"\x15Slave_ReportLoadLevel\x12\x14\n" +
	"\x05isFix\x18\x01 \x01(\bR\x05isFix\x12\x1c\n" +
	"\tAServerID\x18\x02 \x01(\rR\tAServerID\x12\x1c\n" +
	"\tBServerID\x18\x03 \x01(\rR\tBServerID\"7\n" +
	"\x17Master_PublishLoadLevel\x12\x1c\n" +
	"\tLoadLevel\x18\x01 \x01(\rR\tLoadLevel\"q\n" +
	"\x17Slave_ReqShiftFixMaster\x12\x1a\n" +
	"\bMasterID\x18\x01 \x01(\rR\bMasterID\x12\x1c\n" +
	"\tAServerID\x18\x02 \x01(\rR\tAServerID\x12\x1c\n" +
	"\tBServerID\x18\x03 \x01(\rR\tBServerID\"q\n" +
	"\x17Slave_RepShiftFixMaster\x12\x1a\n" +
	"\bMasterID\x18\x01 \x01(\rR\bMasterID\x12\x1c\n" +
	"\tAServerID\x18\x02 \x01(\rR\tAServerID\x12\x1c\n" +
	"\tBServerID\x18\x03 \x01(\rR\tBServerID\"5\n" +
	"\x19Slave_ReqVerifyConfigFile\x12\x18\n" +
	"\aFileMd5\x18\x01 \x01(\tR\aFileMd5\"\x92\x01\n" +
	"\x1aMaster_ReqVerifyConfigFile\x12\x18\n" +
	"\aFileMd5\x18\x01 \x01(\tR\aFileMd5\x12\x12\n" +
	"\x04Time\x18\x02 \x01(\x03R\x04Time\x12 \n" +
	"\vReqServerId\x18\x03 \x01(\rR\vReqServerId\x12$\n" +
	"\rReqServerType\x18\x04 \x01(\rR\rReqServerType\"\x8f\x01\n" +
	"\x19Slave_RepVerifyConfigFile\x12\x16\n" +
	"\x06IsSucc\x18\x01 \x01(\bR\x06IsSucc\x12\x12\n" +
	"\x04Time\x18\x02 \x01(\x03R\x04Time\x12 \n" +
	"\vReqServerId\x18\x03 \x01(\rR\vReqServerId\x12$\n" +
	"\rReqServerType\x18\x04 \x01(\rR\rReqServerType\".\n" +
	"\x12Slave_UptConfigMd5\x12\x18\n" +
	"\aFileMd5\x18\x01 \x01(\tR\aFileMd5\"\x1a\n" +
	"\x18SS_CmdPrepareCloseServer\"\x1a\n" +
	"\x18SM_ReqPrepareCloseMyself\"\x13\n" +
	"\x11SS_CmdCloseServer\"\x15\n" +
	"\x13S2S_CmdUnloadServer\"\x15\n" +
	"\x13S2M_ReqUnloadMyselfB\rZ\v/netclusterb\x06proto3"

var (
	file_netcluster_message_proto_rawDescOnce sync.Once
	file_netcluster_message_proto_rawDescData []byte
)

func file_netcluster_message_proto_rawDescGZIP() []byte {
	file_netcluster_message_proto_rawDescOnce.Do(func() {
		file_netcluster_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_netcluster_message_proto_rawDesc), len(file_netcluster_message_proto_rawDesc)))
	})
	return file_netcluster_message_proto_rawDescData
}

var file_netcluster_message_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_netcluster_message_proto_goTypes = []any{
	(*Master_PublishServerStatus)(nil), // 0: netcluster.Master_PublishServerStatus
	(*Slave_ReportLoadLevel)(nil),      // 1: netcluster.Slave_ReportLoadLevel
	(*Master_PublishLoadLevel)(nil),    // 2: netcluster.Master_PublishLoadLevel
	(*Slave_ReqShiftFixMaster)(nil),    // 3: netcluster.Slave_ReqShiftFixMaster
	(*Slave_RepShiftFixMaster)(nil),    // 4: netcluster.Slave_RepShiftFixMaster
	(*Slave_ReqVerifyConfigFile)(nil),  // 5: netcluster.Slave_ReqVerifyConfigFile
	(*Master_ReqVerifyConfigFile)(nil), // 6: netcluster.Master_ReqVerifyConfigFile
	(*Slave_RepVerifyConfigFile)(nil),  // 7: netcluster.Slave_RepVerifyConfigFile
	(*Slave_UptConfigMd5)(nil),         // 8: netcluster.Slave_UptConfigMd5
	(*SS_CmdPrepareCloseServer)(nil),   // 9: netcluster.SS_CmdPrepareCloseServer
	(*SM_ReqPrepareCloseMyself)(nil),   // 10: netcluster.SM_ReqPrepareCloseMyself
	(*SS_CmdCloseServer)(nil),          // 11: netcluster.SS_CmdCloseServer
	(*S2S_CmdUnloadServer)(nil),        // 12: netcluster.S2S_CmdUnloadServer
	(*S2M_ReqUnloadMyself)(nil),        // 13: netcluster.S2M_ReqUnloadMyself
}
var file_netcluster_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_netcluster_message_proto_init() }
func file_netcluster_message_proto_init() {
	if File_netcluster_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_netcluster_message_proto_rawDesc), len(file_netcluster_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_netcluster_message_proto_goTypes,
		DependencyIndexes: file_netcluster_message_proto_depIdxs,
		MessageInfos:      file_netcluster_message_proto_msgTypes,
	}.Build()
	File_netcluster_message_proto = out.File
	file_netcluster_message_proto_goTypes = nil
	file_netcluster_message_proto_depIdxs = nil
}
