// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: cmsg/client_msg.proto

// 客户端与服务端交互协议

package cmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_OK      Code = 0
	Code_Unknown Code = 1
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0: "OK",
		1: "Unknown",
	}
	Code_value = map[string]int32{
		"OK":      0,
		"Unknown": 1,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_cmsg_client_msg_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_cmsg_client_msg_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_cmsg_client_msg_proto_rawDescGZIP(), []int{0}
}

// 登录服务器并进入聊天室
type CReqLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CReqLogin) Reset() {
	*x = CReqLogin{}
	mi := &file_cmsg_client_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CReqLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CReqLogin) ProtoMessage() {}

func (x *CReqLogin) ProtoReflect() protoreflect.Message {
	mi := &file_cmsg_client_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CReqLogin.ProtoReflect.Descriptor instead.
func (*CReqLogin) Descriptor() ([]byte, []int) {
	return file_cmsg_client_msg_proto_rawDescGZIP(), []int{0}
}

func (x *CReqLogin) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type SRespLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=cmsg.Code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRespLogin) Reset() {
	*x = SRespLogin{}
	mi := &file_cmsg_client_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRespLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRespLogin) ProtoMessage() {}

func (x *SRespLogin) ProtoReflect() protoreflect.Message {
	mi := &file_cmsg_client_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRespLogin.ProtoReflect.Descriptor instead.
func (*SRespLogin) Descriptor() ([]byte, []int) {
	return file_cmsg_client_msg_proto_rawDescGZIP(), []int{1}
}

func (x *SRespLogin) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_OK
}

// 发送聊天消息
type CReqSendChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CReqSendChatMessage) Reset() {
	*x = CReqSendChatMessage{}
	mi := &file_cmsg_client_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CReqSendChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CReqSendChatMessage) ProtoMessage() {}

func (x *CReqSendChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmsg_client_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CReqSendChatMessage.ProtoReflect.Descriptor instead.
func (*CReqSendChatMessage) Descriptor() ([]byte, []int) {
	return file_cmsg_client_msg_proto_rawDescGZIP(), []int{2}
}

func (x *CReqSendChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SRespSendChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=cmsg.Code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRespSendChatMessage) Reset() {
	*x = SRespSendChatMessage{}
	mi := &file_cmsg_client_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRespSendChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRespSendChatMessage) ProtoMessage() {}

func (x *SRespSendChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmsg_client_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRespSendChatMessage.ProtoReflect.Descriptor instead.
func (*SRespSendChatMessage) Descriptor() ([]byte, []int) {
	return file_cmsg_client_msg_proto_rawDescGZIP(), []int{3}
}

func (x *SRespSendChatMessage) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_OK
}

// 有其他玩家进入聊天室
type SNotifyUserEnter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SNotifyUserEnter) Reset() {
	*x = SNotifyUserEnter{}
	mi := &file_cmsg_client_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SNotifyUserEnter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNotifyUserEnter) ProtoMessage() {}

func (x *SNotifyUserEnter) ProtoReflect() protoreflect.Message {
	mi := &file_cmsg_client_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNotifyUserEnter.ProtoReflect.Descriptor instead.
func (*SNotifyUserEnter) Descriptor() ([]byte, []int) {
	return file_cmsg_client_msg_proto_rawDescGZIP(), []int{4}
}

func (x *SNotifyUserEnter) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

// 有其他玩家离开聊天室
type SNotifyUserLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SNotifyUserLeave) Reset() {
	*x = SNotifyUserLeave{}
	mi := &file_cmsg_client_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SNotifyUserLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNotifyUserLeave) ProtoMessage() {}

func (x *SNotifyUserLeave) ProtoReflect() protoreflect.Message {
	mi := &file_cmsg_client_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNotifyUserLeave.ProtoReflect.Descriptor instead.
func (*SNotifyUserLeave) Descriptor() ([]byte, []int) {
	return file_cmsg_client_msg_proto_rawDescGZIP(), []int{5}
}

func (x *SNotifyUserLeave) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

// 同步其他玩家的聊天消息
type SNotifyUserChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SNotifyUserChatMessage) Reset() {
	*x = SNotifyUserChatMessage{}
	mi := &file_cmsg_client_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SNotifyUserChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNotifyUserChatMessage) ProtoMessage() {}

func (x *SNotifyUserChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmsg_client_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNotifyUserChatMessage.ProtoReflect.Descriptor instead.
func (*SNotifyUserChatMessage) Descriptor() ([]byte, []int) {
	return file_cmsg_client_msg_proto_rawDescGZIP(), []int{6}
}

func (x *SNotifyUserChatMessage) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SNotifyUserChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_cmsg_client_msg_proto protoreflect.FileDescriptor

const file_cmsg_client_msg_proto_rawDesc = "" +
	"\n" +
	"\x15cmsg/client_msg.proto\x12\x04cmsg\"%\n" +
	"\tCReqLogin\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\",\n" +
	"\n" +
	"SRespLogin\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\x0e2\n" +
	".cmsg.CodeR\x04code\")\n" +
	"\x13CReqSendChatMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"6\n" +
	"\x14SRespSendChatMessage\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\x0e2\n" +
	".cmsg.CodeR\x04code\",\n" +
	"\x10SNotifyUserEnter\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\",\n" +
	"\x10SNotifyUserLeave\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\"F\n" +
	"\x16SNotifyUserChatMessage\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text*\x1b\n" +
	"\x04Code\x12\x06\n" +
	"\x02OK\x10\x00\x12\v\n" +
	"\aUnknown\x10\x01B\aZ\x05/cmsgb\x06proto3"

var (
	file_cmsg_client_msg_proto_rawDescOnce sync.Once
	file_cmsg_client_msg_proto_rawDescData []byte
)

func file_cmsg_client_msg_proto_rawDescGZIP() []byte {
	file_cmsg_client_msg_proto_rawDescOnce.Do(func() {
		file_cmsg_client_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmsg_client_msg_proto_rawDesc), len(file_cmsg_client_msg_proto_rawDesc)))
	})
	return file_cmsg_client_msg_proto_rawDescData
}

var file_cmsg_client_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmsg_client_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cmsg_client_msg_proto_goTypes = []any{
	(Code)(0),                      // 0: cmsg.Code
	(*CReqLogin)(nil),              // 1: cmsg.CReqLogin
	(*SRespLogin)(nil),             // 2: cmsg.SRespLogin
	(*CReqSendChatMessage)(nil),    // 3: cmsg.CReqSendChatMessage
	(*SRespSendChatMessage)(nil),   // 4: cmsg.SRespSendChatMessage
	(*SNotifyUserEnter)(nil),       // 5: cmsg.SNotifyUserEnter
	(*SNotifyUserLeave)(nil),       // 6: cmsg.SNotifyUserLeave
	(*SNotifyUserChatMessage)(nil), // 7: cmsg.SNotifyUserChatMessage
}
var file_cmsg_client_msg_proto_depIdxs = []int32{
	0, // 0: cmsg.SRespLogin.code:type_name -> cmsg.Code
	0, // 1: cmsg.SRespSendChatMessage.code:type_name -> cmsg.Code
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cmsg_client_msg_proto_init() }
func file_cmsg_client_msg_proto_init() {
	if File_cmsg_client_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmsg_client_msg_proto_rawDesc), len(file_cmsg_client_msg_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmsg_client_msg_proto_goTypes,
		DependencyIndexes: file_cmsg_client_msg_proto_depIdxs,
		EnumInfos:         file_cmsg_client_msg_proto_enumTypes,
		MessageInfos:      file_cmsg_client_msg_proto_msgTypes,
	}.Build()
	File_cmsg_client_msg_proto = out.File
	file_cmsg_client_msg_proto_goTypes = nil
	file_cmsg_client_msg_proto_depIdxs = nil
}
