// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: cmsg/client_msg.proto

// 客户端与服务端交互协议

package cmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ================== 输入指令 ==================
type InputCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Up            bool                   `protobuf:"varint,1,opt,name=up,proto3" json:"up,omitempty"`       // W键
	Left          bool                   `protobuf:"varint,2,opt,name=left,proto3" json:"left,omitempty"`   // A键
	Down          bool                   `protobuf:"varint,3,opt,name=down,proto3" json:"down,omitempty"`   // S键
	Right         bool                   `protobuf:"varint,4,opt,name=right,proto3" json:"right,omitempty"` // D键
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputCommand) Reset() {
	*x = InputCommand{}
	mi := &file_cmsg_client_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputCommand) ProtoMessage() {}

func (x *InputCommand) ProtoReflect() protoreflect.Message {
	mi := &file_cmsg_client_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputCommand.ProtoReflect.Descriptor instead.
func (*InputCommand) Descriptor() ([]byte, []int) {
	return file_cmsg_client_msg_proto_rawDescGZIP(), []int{0}
}

func (x *InputCommand) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

func (x *InputCommand) GetLeft() bool {
	if x != nil {
		return x.Left
	}
	return false
}

func (x *InputCommand) GetDown() bool {
	if x != nil {
		return x.Down
	}
	return false
}

func (x *InputCommand) GetRight() bool {
	if x != nil {
		return x.Right
	}
	return false
}

// ================== 玩家指令集 ==================
type PlayerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Commands      []*InputCommand        `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"` // 该玩家的所有指令
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_cmsg_client_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_cmsg_client_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_cmsg_client_msg_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerInput) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerInput) GetCommands() []*InputCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

// 新玩家刚进入，同步一次状态
type PlayerEnter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEnter) Reset() {
	*x = PlayerEnter{}
	mi := &file_cmsg_client_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEnter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEnter) ProtoMessage() {}

func (x *PlayerEnter) ProtoReflect() protoreflect.Message {
	mi := &file_cmsg_client_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEnter.ProtoReflect.Descriptor instead.
func (*PlayerEnter) Descriptor() ([]byte, []int) {
	return file_cmsg_client_msg_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerEnter) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerEnter) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerEnter) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerEnter) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

// 某个玩家离开
type PlayerLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeave) Reset() {
	*x = PlayerLeave{}
	mi := &file_cmsg_client_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeave) ProtoMessage() {}

func (x *PlayerLeave) ProtoReflect() protoreflect.Message {
	mi := &file_cmsg_client_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeave.ProtoReflect.Descriptor instead.
func (*PlayerLeave) Descriptor() ([]byte, []int) {
	return file_cmsg_client_msg_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerLeave) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

var File_cmsg_client_msg_proto protoreflect.FileDescriptor

const file_cmsg_client_msg_proto_rawDesc = "" +
	"\n" +
	"\x15cmsg/client_msg.proto\x12\x04cmsg\"\\\n" +
	"\fInputCommand\x12\x0e\n" +
	"\x02up\x18\x01 \x01(\bR\x02up\x12\x12\n" +
	"\x04left\x18\x02 \x01(\bR\x04left\x12\x12\n" +
	"\x04down\x18\x03 \x01(\bR\x04down\x12\x14\n" +
	"\x05right\x18\x04 \x01(\bR\x05right\"Y\n" +
	"\vPlayerInput\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\x04R\bplayerId\x12.\n" +
	"\bcommands\x18\x02 \x03(\v2\x12.cmsg.InputCommandR\bcommands\"[\n" +
	"\vPlayerEnter\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\x04R\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\")\n" +
	"\vPlayerLeave\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\x04R\bplayerIdB\aZ\x05/cmsgb\x06proto3"

var (
	file_cmsg_client_msg_proto_rawDescOnce sync.Once
	file_cmsg_client_msg_proto_rawDescData []byte
)

func file_cmsg_client_msg_proto_rawDescGZIP() []byte {
	file_cmsg_client_msg_proto_rawDescOnce.Do(func() {
		file_cmsg_client_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmsg_client_msg_proto_rawDesc), len(file_cmsg_client_msg_proto_rawDesc)))
	})
	return file_cmsg_client_msg_proto_rawDescData
}

var file_cmsg_client_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cmsg_client_msg_proto_goTypes = []any{
	(*InputCommand)(nil), // 0: cmsg.InputCommand
	(*PlayerInput)(nil),  // 1: cmsg.PlayerInput
	(*PlayerEnter)(nil),  // 2: cmsg.PlayerEnter
	(*PlayerLeave)(nil),  // 3: cmsg.PlayerLeave
}
var file_cmsg_client_msg_proto_depIdxs = []int32{
	0, // 0: cmsg.PlayerInput.commands:type_name -> cmsg.InputCommand
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cmsg_client_msg_proto_init() }
func file_cmsg_client_msg_proto_init() {
	if File_cmsg_client_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmsg_client_msg_proto_rawDesc), len(file_cmsg_client_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmsg_client_msg_proto_goTypes,
		DependencyIndexes: file_cmsg_client_msg_proto_depIdxs,
		MessageInfos:      file_cmsg_client_msg_proto_msgTypes,
	}.Build()
	File_cmsg_client_msg_proto = out.File
	file_cmsg_client_msg_proto_goTypes = nil
	file_cmsg_client_msg_proto_depIdxs = nil
}
